#!/usr/bin/env bash

if ! command -v brew &> /dev/null
then
    echo "-> Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "-> Downloading latest antigen.zsh"
curl -sL git.io/antigen > ~/.dotfiles/antigen.zsh

if [ ! -f ~/.zshrc ]; then
    echo "-> Copying .zshrc to home folder"
    cp zshrc.original ~/.zshrc
    echo
    echo "Close this terminal and open a new one and run script/setup again from ~/.dotfiles directory."
    echo
    exit 1
fi

echo "-> Importing Terminal themes"
~/.dotfiles/themes/import.sh
