#!/usr/bin/env bash

if [[ $OSTYPE == linux* ]]; then
  SHELL=$(which zsh)
  export SHELL=$SHELL
  exec $SHELL -l
fi

DOTFILES_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && cd ../ &> /dev/null && pwd )

if [ ! -d ~/.dotfiles ]; then
  ln -s $DOTFILES_DIR ~/.dotfiles
fi

if [ ! -f ~/.gitconfig ]; then
  echo "-> Symlinking .gitconfig"
  ln -s ~/.dotfiles/.gitconfig-global ~/.gitconfig
fi

if [ ! -f ~/.gitignore ]; then
  echo "-> Symlinking .gitignore"
  ln -s ~/.dotfiles/.gitignore-global ~/.gitignore
fi

echo "-> Downloading latest antigen.zsh"
curl -sL git.io/antigen > ~/.dotfiles/antigen.zsh

if [ ! -f ~/.zshrc ]; then
  echo "-> Copying .zshrc to home folder"
  cp zshrc.original ~/.zshrc
  bash -c zsh
  source ~/.zshrc
fi

if [[ $OSTYPE == darwin* ]]; then
  if ! command -v brew &> /dev/null; then
    echo "-> Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  echo "-> Installing homebrew packages"
  brew update
  brew bundle --file=~/.dotfiles/install/Brewfile

  if [[ $CPUTYPE == arm64 ]]; then
    echo "-> Installing homebrew Cask packages"
    brew bundle --file=~/.dotfiles/install/Caskfile
  fi

  if ! plutil -extract Window\ Settings.One\ Dark xml1 -o - ~/Library/Preferences/com.apple.Terminal.plist > /dev/null; then
    echo "-> Importing Terminal themes"
    ~/.dotfiles/themes/import.sh
  fi

  if [ ! -d ~/github ]; then
    echo "-> Creating ~/github directory"
    mkdir -p ~/github
  fi

  if [ ! -d ~/github/vpn ]; then
    echo "-> Cloning github/vpn"
    cd ~/github
    git clone https://github.com/github/vpn
  fi
fi
