#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "-> Downloading latest antigen.zsh"
curl -sL git.io/antigen > $SCRIPT_DIR/../antigen.zsh

if [ ! -f ~/.zshrc ]; then
  echo "-> Copying .zshrc to home folder"
  cp zshrc.original ~/.zshrc
  bash -c zsh
  source ~/.zshrc
fi

if [[ $OSTYPE == darwin* ]]; then
  if ! command -v brew &> /dev/null; then
    echo "-> Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  echo "-> Installing homebrew packages"
  brew update
  brew bundle --file=$SCRIPT_DIR/../install/Brewfile

  if [[ $CPUTYPE == arm64 ]]; then
    echo "-> Installing homebrew Cask packages"
    brew bundle --file=$SCRIPT_DIR/../install/Caskfile
  fi

  if ! plutil -extract Window\ Settings.One\ Dark xml1 -o - ~/Library/Preferences/com.apple.Terminal.plist > /dev/null; then
    echo "-> Importing Terminal themes"
    $SCRIPT_DIR/../themes/import.sh
  fi

  if [ ! -d ~/github ]; then
    echo "-> Creating ~/github directory"
    mkdir -p ~/github
  fi

  if [ ! -d ~/github/vpn ]; then
    echo "-> Cloning github/vpn"
    cd ~/github
    git clone https://github.com/github/vpn
  fi
fi
